# Generated by Django 3.2.7 on 2021-09-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=32)),
                ('machine_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'files_info',
            },
        ),
    ]
