# Generated by Django 3.2.7 on 2021-09-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0003_auto_20210914_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_info',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='ip_address',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='machine_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='md5_fn',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
