# Generated by Django 3.2.7 on 2021-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0004_auto_20210914_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_info',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files_info',
            name='md5_fn',
            field=models.CharField(max_length=64),
        ),
    ]
