# Generated by Django 3.2.7 on 2021-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0006_auto_20210914_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_info',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files_info',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files_info',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='file_name',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='md5_fn',
            field=models.CharField(max_length=64),
        ),
    ]
