# Generated by Django 3.2.7 on 2021-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0007_auto_20210914_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_info',
            name='downloads',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='state',
            field=models.BooleanField(),
        ),
    ]
