# Generated by Django 3.2.7 on 2021-09-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0008_auto_20210914_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_info',
            name='create_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='files_info',
            name='state',
            field=models.BooleanField(default=1),
        ),
    ]
