# Generated by Django 3.2.7 on 2021-09-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0010_auto_20210914_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_info',
            name='create_dt',
        ),
        migrations.RemoveField(
            model_name='files_info',
            name='id',
        ),
        migrations.AddField(
            model_name='files_info',
            name='file_name',
            field=models.CharField(db_index=True, default=2, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
