# Generated by Django 3.2.7 on 2021-09-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0012_auto_20210914_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_info',
            name='create_dt',
        ),
        migrations.RemoveField(
            model_name='files_info',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='files_info',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='files_info',
            name='machine_code',
        ),
        migrations.RemoveField(
            model_name='files_info',
            name='md5_fn',
        ),
    ]
