# Generated by Django 3.2.7 on 2021-09-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UP_FileLoad', '0022_auto_20210914_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files_Info',
        ),
    ]
