# Generated by Django 3.2.7 on 2021-09-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UP_FileLoad', '0023_delete_files_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files_Info',
            fields=[
                ('file_name', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('md5_fn', models.CharField(default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('machine_code', models.CharField(default='', max_length=255)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'files_info',
            },
        ),
    ]
